# 6 oct 2025

# Working with arrays

In [1]:
import numpy as np
# ARRAY CONCATENATION
# creo un array concatenando x e y (sopra x e sotto y)
# il risultati ha lo stessi numero di dimensioni degli array di input
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
np.concatenate((x, y)) # Default axis: 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
np.concatenate((x, y), axis=1) # concatetanation along rows

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [3]:
# hstack, vstack
# instaead of using concatenate
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
h = np.hstack((x, y)) # along rows (horizontal)
v = np.vstack((x, y)) # along columns (vertical)

In [4]:
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [5]:
h

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [6]:
# vstack allows concatenating 1-D vectors along new
# axis (not possible with np.concatenate)
# ho due array 1D come input e l'output diventa 2D (usando concatenate non potrei)
x = np.array([1,2,3])
y = np.array([11,12,13])
v = np.vstack((x, y)) # vertically
v

array([[ 1,  2,  3],
       [11, 12, 13]])

In [7]:
# SPLITTING ARRAYS

In [11]:
# outputs a list of Numpy arrays
# If N is integer: divide arr into N equal arrays (along axis), if possible!
# if N is a 1d array: specify the entries where the array is split (along axis)
x = np.array([7, 7, 9, 9, 8, 8])
# taglio prima dell'elemento 2 e poi taglio prima dell'elemento 4
np.split(x,[2,4]) # split before element 2 and 4 # same as passing N = 3

[array([7, 7]), array([9, 9]), array([8, 8])]

In [17]:
# hsplit, vsplit with 2D arrays
# return a list with the arrays after the split
x = np.array([[1, 2, 3, 11, 12, 13], [4, 5, 6, 14, 15, 16]])
np.hsplit(x, [3]) # splitto prima dell'indice 3
#np.vsplit(x, 2) # 2 arrays of equal size (along axis 0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [18]:
# RESHAPING ARRAYS
x = np.arange(6)
# voglio ridimensionare x seguendo la shape (2,3) --> posiziona in 2 righe e 3 colonne
y = x.reshape((2,3))
x, y

(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [20]:
# At most one dimension can be -1 (“unknown”)
# If present, the size is inferred (dedotta) from
# - The source array
# - The other dimensions
x = np.array([1,2,3])
y = x.reshape(-1,1) # The first dimension (rows) is inferred to be 3, considering that the second dimension (columns) is 1 and x.size = 3
x, y # trasformo x in 3 righe e 1 colonna, ho dedotto le righe guardando la size

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

In [22]:
# c-like, fortran-like
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# C-like # ridimensiona mettendo gli elementi in 3 righe e 4 colonne. 
# Riempie una riga alla volta con gli elementi dell'array orgininale
y = x.reshape(3,4, order="C")
# F-like # ridimensiona mettendo gli elementi in 3 righe e 4 colonne
# Riempe una colonna alla volta con gli elementi dell'array originale
z = x.reshape(3,4, order="F") # F-like
y,z


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]]))

In [23]:
# ADDING NEW DIMENSIONS
# np.newaxis adds a new dimension with shape=1 at the specified position
arr = np.array([[1,2,3],[4,5,6]])
# we can use also reshape and obtain the same solution (it is better using reshape)
res = arr[np.newaxis, :, :] # output shape = (1,2,3) # ho aggiunto una dimensione
res

array([[[1, 2, 3],
        [4, 5, 6]]])

In [24]:
#row vector to column vector
# Alternative approach to .reshape(-1,1) where a dimension can be unknown
arr = np.array([1,2,3])
res = arr[:, np.newaxis] # output shape = (3,1)
res

array([[1],
       [2],
       [3]])