In [1]:
# 01/10/2025
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([0, 2, 1])
x

array([1, 2, 3])

In [3]:
y

array([0, 2, 1])

In [4]:
# algebric operations
# prodotto scalare = inner product, 
# inner product if x and y are two 1D arrays
# you can also multply matrix by vector or matrix by matrix
x @ y

np.int32(7)

In [5]:
# normalization
def norm2(x):
    return ((x ** 2).sum())**0.5
norm2(x)

np.float64(3.7416573867739413)

In [6]:
norm2(y)

np.float64(2.23606797749979)

In [7]:
# BROADCASTING is a way for us to perform operation that tipically 
# are done on matrices with the same shape but also with different shape
# I can repeat row vetor or column vector a bunch of time in order 
# to have the same shape and make operations between two matrices

# broadcasting has to have sense

In [8]:
# one of the dimension has to match with the other array.
# RULES of BROADCASTING
# 1) The shape of the array with fewer dimensions is padded with leading ones

# 2) if the shape along a dimension is 1 for one of the arrays and > 1 for the other,
# the array with shape = 1 in that dimension is stretched to match the other array

# 3) If there is a dimension where both arrays have shape > 1 and those shapes differ, then broadcasting cannot be performed
# if there is not match between each dimension (all different from 1), 
# so we cannot compute broadcasting



In [41]:
# Ex broadcasting
x = np.array([1, 2, 3]) # shape (3, )
y = np.array([[11], [12], [13]]) # shape (3,1)
z = x + y
z # broadcasting is applied into x and y in order to reach the same shape
# rule 1) x.shape becomes (1, 3): x=[[1,2,3]]
# rule 2) extend x on the vertical axis, y on the horizontal one

array([[12, 13, 14],
       [13, 14, 15],
       [14, 15, 16]])

In [10]:
a = np.array([[1, 2], [3, 4], [5, 6]]) # shape (3, 2)
b = np.array([11, 12, 13]) # shape(3, )
# c = a + b
# c 
# numpy will raise an exception beacuse of dimensions, after applying rule 1, are incompatibles

In [11]:
X = np.random.random((100, 5))
X.mean(axis=0) # I get the mean on axis 0

array([0.46498056, 0.47761931, 0.44359956, 0.51254604, 0.49955483])

In [12]:
(X - X.mean(axis=0)).mean(axis=0)

array([ 4.88498131e-17,  3.10862447e-17,  1.72084569e-17, -1.68753900e-16,
        3.66373598e-17])

In [13]:
X.shape # the shape of X is (100, 5)

(100, 5)

In [14]:
X.mean(axis=0).shape  # the shaoe of this array is (5,)
# it is possible to broadcasting arrays with (5,1), after applying rule 1), and (100,5) shape

(5,)

In [15]:
#(X - X.mean(axis=0)) / X.std(axis=0)

In [16]:
# ACCESSING NUMPY ARRAYS
x = np.random.randint(1, 10, (3, 2))

In [17]:
x

array([[6, 1],
       [2, 9],
       [6, 4]])

In [18]:
# SIMPLE-INDEXING 
# we can also use negative indices 
x[0, 1] # I want row 0, element in column 1 => 8

np.int32(1)

In [19]:
x[0] # I want row 1
# with simple indexing we can also assign value to a specific element

array([6, 1])

In [20]:
# SLICING
# x[start:stop:step] stop is excluded
# creates a view of the elements from start to stop with step
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:, 1:] # all elements in dimension 1 (prendo tutte le righe), 
# from the second element to the last element of dimension 2 (prendo tutte le colonne a partire dalla seconda)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [21]:
x[:2, ::2]  # or x[0:2, 0:3:2]
# select the first two rows (per le righe prende dall'inizio alla terza riga esclusa, quindi prende la prima e la seconda)
# select the first and third column (per le colonne prende dall'inizio alla fine con step 2, quindi prende la prima colonna e la terza)

array([[1, 3],
       [4, 6]])

In [22]:
# we can update a sliced array
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:, 1:] = 0
x # replaces in all rows and from the second column onwards with 0s 
# (sostituisce in tutte le righe e dalla seconda colonna in avanti con degli 0)

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

In [23]:
# To avoid updating the original array use .copy()

In [24]:
# MASKING
# use boolena masks to select elements
# masking and fancy indexing provide copies of the array
# if I pass a mask, I select some elements of the array
# the mask is boolean and with the same shape of the array
x = np.random.random(5)
x

array([0.36899291, 0.47346893, 0.54657338, 0.46755512, 0.34890613])

In [25]:
mask = [False, True, True, False, False]
x[mask] # I select only the elements that match with True value of the mask
# The result is a one-dimensional vector that is a copy of the original array elements selected by the mask

array([0.47346893, 0.54657338])

In [47]:
x = np.array([1.2, 4.1, 1.5, 4.5])
x > 4 # if you want to filter 

array([False,  True, False,  True])

In [27]:
mask1 = (x > 0.2)
mask1

array([ True,  True,  True,  True,  True])

In [28]:
mask2 = (x < 0.3)
mask2
# Even if the shape of x2 is (2, 2), the result is a one-dimensional array containing the elements that satisfy the condition

array([False, False, False, False, False])

In [29]:
# you can also apply boolean algebra 
# & (and), | (or), ^ (xor), ~ (negation)
mask3 = ~((x < 0.2) | (x > 0.5)) # ((x >= 0.1) & (x <= 0.5))
mask3

array([ True,  True, False,  True,  True])

In [30]:
# in masking you can update array
# Masking does not create views, but copies

In [31]:
# FANCY INDEXING
# specify the index of elements to be selected
x = np.array([7.0, 9.0, 6.0, 5.0])
# I can specify a list of indeces I want to get in the first dimension
x[[1, 3]]

array([9., 5.])

In [32]:
# I can specicy coordinate of array of multiple dimensions
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
x[[0, 2], [0, 1]] # first the indices of the first dimension and then the indices of the second dimension

array([0., 7.])

In [33]:
#Similarly to masking, fancy indexing provides copies (not views) of the original array

In [34]:
# COMBINED INDEXING
# we can mix methods of indexing
# The number of dimensions of selected data is: 
# - The same as the input if you mix: masking+slicing, fancy+slicing
# - Reduced by one for each axis where simple indexing is used because simple indexing takes only 1 single element from an axis
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [35]:
x[[True,False,True], 1:] # The result is the first and the third row, and the second and third column
# Masking + Slicing: [[1.0,2.0],[7.0,8.0]]
# Output has the same numer of dimensions as input

array([[1., 2.],
       [7., 8.]])

In [36]:
x[[0,2], :2] # The output is the rows with indices 0 and 2 (the first and the third) and the first and second column
# Fancy + Slicing: [[0.0,1.0],[6.0,7.0]]
# Output has the same numer of dimensions as input

array([[0., 1.],
       [6., 7.]])

In [38]:
# Simple indexing reduces the number of dimensions
# simple indexing + slicing
# The dimension selected with simple indexing is removed from the output
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])

In [39]:
x[0, 1:] # the result the row with indix 0 with second and third column
# Simple + Slicing: [1.0, 2.0]

array([1., 2.])

In [40]:
x[[True, False, True], 0] # the output is the first and third row and the column with index 0, the first column
# Simple + Masking: [0.0, 6.0]

array([0., 6.])