In [1]:
import numpy as np

In [2]:
n=5

In [3]:
# array random shape n*n con valori uniformamente distribuiti tra 0 e 1
A = np.random.random((n, n))
B = np.random.random((n, n))

In [4]:
A

array([[0.13356269, 0.18513803, 0.09201615, 0.36815217, 0.33039975],
       [0.85807263, 0.82887215, 0.28635455, 0.27140228, 0.36885528],
       [0.8273608 , 0.08147999, 0.59210342, 0.83050004, 0.08801617],
       [0.96651132, 0.237507  , 0.39231143, 0.45512362, 0.2657317 ],
       [0.3827034 , 0.41224672, 0.0526505 , 0.94776917, 0.75078384]])

In [5]:
B

array([[0.86876408, 0.4260249 , 0.86704387, 0.91455665, 0.79123103],
       [0.83475498, 0.51879811, 0.00823925, 0.80906374, 0.37059589],
       [0.80705928, 0.46320571, 0.7307102 , 0.33882214, 0.54712338],
       [0.67789896, 0.81205075, 0.64913871, 0.00131011, 0.67099092],
       [0.85520693, 0.21641376, 0.79213432, 0.3763589 , 0.26737531]])

In [6]:
A+B

array([[1.00232677, 0.61116293, 0.95906002, 1.28270883, 1.12163078],
       [1.69282761, 1.34767025, 0.2945938 , 1.08046603, 0.73945117],
       [1.63442008, 0.5446857 , 1.32281362, 1.16932219, 0.63513956],
       [1.64441028, 1.04955776, 1.04145014, 0.45643373, 0.93672261],
       [1.23791033, 0.62866047, 0.84478482, 1.32412807, 1.01815915]])

In [7]:
# creazione semplice array indicando i valori 
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [8]:
# array di zero con shape 3*2
arr2 = np.zeros((3,2))
arr2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
# array di uno con shape 2*3
arr3 = np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# array con  tutti i gli elementi a value 1.8, con la shape 3*2
arr4 = np.full((3,2), 1.8)
arr4

array([[1.8, 1.8],
       [1.8, 1.8],
       [1.8, 1.8]])

In [11]:
# array with num =11 samples from start=0 to stop=1 (included) c
arr5 =np.linspace(0,1,11)
arr5

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
# array with numbers from start=1 to stop=7 (excluded) with step=2
arr6 = np.arange(1,7,2)
arr6

array([1, 3, 5])

In [13]:
# array with random data with normal distribution (mean, std, shape)
arr7 = np.random.normal(2,3.4,(3,2))
arr7

array([[ 1.06393012,  2.05800219],
       [ 1.99710742, -0.84880049],
       [-0.34819838, -2.30629867]])

In [14]:
# array with random data uniformly distribuited in [0,1] with shape 3*2
arr8 = np.random.random((3, 2))
arr8

array([[0.21262724, 0.93806573],
       [0.01493201, 0.94460314],
       [0.56127664, 0.17434819]])

In [16]:
x = np.array([[2, 3, 4], [5, 6, 7]])
# number of dimensions of the array
x.ndim

2

In [17]:
# tuple with the array shape
x.shape

(2, 3)

In [18]:
# array size (product of the shape values)
x.size

6

In [19]:
# binary operations with array of the same shape (+, -, *, /, %, //, **)
a = np.array([[1,1], [2, 2]])
b = np.array([[3,4], [6, 5]])
a*b

array([[ 3,  4],
       [12, 10]])

In [21]:
# unary operations (abs, exp, log, log2, sin, cos, tab, arctan) apply the operation separately to each eleemnt of the array
# original array is not modiefied
np.log(a)

array([[0.        , 0.        ],
       [0.69314718, 0.69314718]])

In [22]:
# aggregate functions --> return a single value from an array (min, max mean, std, sum, argmin, argmax)

# argmin, argmax
# for 1 dimensional array return the position of the smallest/ largest element of the array
c = np.array([5, 3, 9, 1, 7])
c.argmin()


np.int32(3)

In [23]:
c.argmax()

np.int32(2)

In [24]:
# for N-dimensional array
# return the position of the smallest/largest element of the flattend(= collapsed into one dimension) version of the array
d = np.array([[8, 3, 9], [4, 2, 9]])
d.argmin()

np.int32(4)

In [25]:
# aggregate functions along axis
# allow specifying the axis along with performing the operation
e = np.random.random((3, 2, 1))
e

array([[[0.09213678],
        [0.41601742]],

       [[0.15997486],
        [0.54605513]],

       [[0.21613635],
        [0.36638069]]])

In [43]:
e.argmax(axis=0)

array([[2],
       [1]])

In [44]:
e.sum(axis=1)

array([[0.5081542 ],
       [0.70602999],
       [0.58251704]])

In [26]:
# the aggregation dimension is removed from the output
e.min(axis=-1) #remove axis -1

array([[0.09213678, 0.41601742],
       [0.15997486, 0.54605513],
       [0.21613635, 0.36638069]])

In [27]:
e.min(axis=1) #remove axis 1

array([[0.09213678],
       [0.15997486],
       [0.21613635]])

In [28]:
# sorting --> array is sorted along the last axis -1 by default (sort along rows)
f = np.random.random((3, 2))
f

array([[0.20443444, 0.61116206],
       [0.37687355, 0.03015014],
       [0.83857846, 0.17002779]])

In [29]:
np.sort(f) # creates a sorted copy, f is not modified 

array([[0.20443444, 0.61116206],
       [0.03015014, 0.37687355],
       [0.17002779, 0.83857846]])

In [32]:
g = np.random.random((3, 2))
g

array([[0.57431515, 0.39379319],
       [0.51880376, 0.20692542],
       [0.69098491, 0.69143204]])

In [34]:
g.sort() # sorts g inplace (g is modified)
g

array([[0.39379319, 0.57431515],
       [0.20692542, 0.51880376],
       [0.69098491, 0.69143204]])

In [35]:
h = np.random.random((3, 2))
h

array([[0.90796286, 0.91214146],
       [0.9650757 , 0.22336062],
       [0.04243741, 0.86252276]])

In [36]:
np.sort(h, axis=0) #sort along columns

array([[0.04243741, 0.22336062],
       [0.90796286, 0.86252276],
       [0.9650757 , 0.91214146]])

In [39]:
# argsort return the posision of the indices of the sorted array (sorted by default on axis -1)
i = np.random.random((2, 3))
i

array([[0.82246441, 0.5865219 , 0.3007934 ],
       [0.26975369, 0.05220457, 0.30784705]])

In [40]:
np.argsort(i)

array([[2, 1, 0],
       [1, 0, 2]])